{% set name = "scotch" %}
{% set build = 0 %}
{% set version = "6.0.5" %}
{% set sha256 = "302c200e0fd4f80ae8992f1c26ad47c734c463bd040b8b7b64469bdb222fe2db" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://gforge.inria.fr/frs/download.php/latestfile/298/scotch_{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patch1.diff

build:
  skip: true  # [win]
  number: {{ build }}

requirements:
 build:
  - toolchain
  - bison
  - flex 2.6.0
  - zlib 1.2.*
  {% if name == 'ptscotch' %}
  - {{ mpi }}
  {% endif %}
 run:
  - zlib 1.2.*
  {% if name == 'ptscotch' %}
  - scotch {{version}}
  - {{ mpi }}
  {% endif %}

test:
  requires:
    - toolchain
  commands:
    {% if name == 'scotch' %}
    - test -f "${PREFIX}/lib/libscotch.a"
    - test -f "${PREFIX}/lib/libscotcherr.a"
    - test -f "${PREFIX}/lib/libscotcherrexit.a"
    - test -f "${PREFIX}/lib/libscotchmetis.a"
    - test -f "${PREFIX}/lib/libesmumps.a"
    - test -f "${PREFIX}/include/scotch.h"
    - test -f "${PREFIX}/include/scotchf.h"
    - test -f "${PREFIX}/include/esmumps.h"
    - test -f "${PREFIX}/include/scotch/metis.h"
    - test ! -f "${PREFIX}/include/metis.h"
    {% else %}
    - test -f "${PREFIX}/lib/libptscotch.a"
    - test -f "${PREFIX}/lib/libptscotcherr.a"
    - test -f "${PREFIX}/lib/libptscotcherrexit.a"
    - test -f "${PREFIX}/lib/libptscotchparmetis.a"
    - test -f "${PREFIX}/lib/libptesmumps.a"
    - test -f "${PREFIX}/include/ptscotch.h"
    - test -f "${PREFIX}/include/ptscotchf.h"
    - test -f "${PREFIX}/include/esmumps.h"
    - test -f "${PREFIX}/include/scotch/parmetis.h"
    - test ! -f "${PREFIX}/include/parmetis.h"
    {% endif %}

about:
  home: https://www.labri.fr/perso/pelegrin/scotch/
  license: CeCILL-C
  license_file: doc/CeCILL-C_V1-en.txt
  {% if name == 'scotch' %}
  summary: 'SCOTCH: Static Mapping, Graph, Mesh and Hypergraph Partitioning, and Parallel and Sequential Sparse Matrix Ordering Package'
  {% else %}
  summary: 'PT-SCOTCH: (Parallel) Static Mapping, Graph, Mesh and Hypergraph Partitioning, and Parallel and Sequential Sparse Matrix Ordering Package'
  {% endif %}
  description: |
    Software package and libraries for sequential and parallel 
    graph partitioning, static mapping and clustering, sequential 
    mesh and hypergraph partitioning, and sequential and parallel 
    sparse matrix block ordering.
  doc_url: http://gforge.inria.fr/docman/?group_id=248&dirid=326

extra:
  recipe-maintainers:
    - basnijholt
    - dalcinl
    - minrk
