matrix:
  - [[SCOTCH_VARIANT, '']]
  - [[SCOTCH_VARIANT, 'pt']]
travis:
  secure:
    BINSTAR_TOKEN: 1BcWxLk60NE8jQsQ+gXIBSd4MUtRcrHeW+Hmknb6gSt2vFKqTgyM/03gREKWIEfzz9sgNyMav8GK2tzXABIGrQUysAo7TNeK1x+Y4trO2W8kUIFm6+GQzRAV66RWXwl99q34o605uHAjdKI47yEaiv0163TqHZQg5hBv4OdHMYecvmJWTL6zNRjIRBXo36xP3Sw6c6n2Zih0A7tRpQx+9Y+dh9Qx+lsdpnhSdCI86FRF4xeiZu52Dz2VCPbXhPOp8dfhRm4oY7WWRBb+fcICX0wDn2Oxsb8O+9L2aerRKUQ4O8I2yYIeWBb0KSowVwdwCx5VIFLR6i+URJNqPtn2Udo254R748M5/1+bWcO+RIgLqLUXZyPn+CSvlpjWpWcgv9S85yskv9RIhaoXq15LjrQhMV1+ru+Q7pEXsNMm9lZ8CYW8IPRov8Oy39oYuEF//P/Weu0WK5AD84pRvd5gFYPJu6/2fRrPShCNvoJMSyhtckHZIJy4+rGZ4WUu6QpFp8WTna4oTMtSX7DVz9WZskkC3s2Gp4Gbbmn9FRBfDyr0tWqMoW6C+Rbh4uRHL4p2NJOtstWRAUu+xiGy7+rJRwEbW6hNfqzbTrt67u/VjRAEHea/sc+kt2CdmLm959q/hnXEsbhPAQczXxFf4rXvgYs4v4jguWCfIu6Gew5Ty/A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
