provider: {linux_aarch64: default, linux_ppc64le: default}
appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: NgtIPzPALtqEVPlUdrPrkHWvxqqDFHxAD6S+csCpNUIsFK373XwFQNJZVZcm5Sg1D5J/tC8+aFs9LM60NVOkPXf9DwLhhR3oRLWbeUZwF51fORhXijio0RplXTal8kqycCsRCGGIKsl3AT8AzPfTBplLIe0k4LX75nEt7e6wF36SHEKz7fuU3XqLwPoO60GMrFqIq0o3hbnKlOIZjQaPOOdrWNcmbsXSmWsm9RYHFCRMoJvPa1hAtX1Vh0BavepqrgYYPQlmfA2fBGeQdaOJ4WclJQ232Bbr18HjG6NOdD8qJPXOMy4pc+M8eMJzrg+S3GN49Mqx3bClZ5DhMvEMWfSFLAQIxCgwXJBNcNwDsLadKPSdinkhXGluvKddyw57B8FSp8qRs5E8JNPu/wVYDMSCV+GGvjWsuAzYfpLd1R4woigHOrIsrCkJiZ6Da+uUC1qZTeIMuJ14ePsSGkPNFnUcXVtyfFSZDWUEXEOwky7rdBgebaE/vE+YdnsqNGjvRknjBz9w3ixMCwEqZMzW56JWZWL8/yreBDvCOo4x+CssIHNLrdjQjh3Qr9YsF7p6eMIj31yeavWAfJ72iINpXtFptt2vlUUbZOTu4RocWUs9g+L3g9L7+pU0K/va8e2tVq39nQgOWI71VQ4IF0TEz8hDpYJbhggFRy1FsB3E8zk=}
